version: '3.8'

services:
  oracle-db:
    image: wnameless/oracle-xe-11g
    environment:
      - ORACLE_PASSWORD=oracle
    ports:
      - "1521:1521"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
